# Generated by Django 3.0.4 on 2020-04-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20200403_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default='we are here', max_length=255),
            preserve_default=False,
        ),
    ]
