# Generated by Django 3.0.4 on 2020-03-11 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='image',
        ),
    ]
