# Generated by Django 3.0.4 on 2020-04-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0003_post_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_caption',
            field=models.CharField(default='talk is cheap show me the code', max_length=255),
            preserve_default=False,
        ),
    ]
